console.log(1+1)
try {
    authUsuario()
} catch (error) {
    console.log(error)
}
console.log(2+2)